// Each new term in the Fibonacci sequence is generated by adding the previous
// two terms.  By starting with 1 and 2, the first 10 terms will be:
//   1, 2, 3, 5, 8, 13, 21, 34, 55, 89
//
// By considering the terms in the Fibonacci sequence whose values do not
// exceed four million, find the sum of the even-valued terms.

#include <stdio.h>
#include <stdlib.h>

// program entry point
int main(int argc, char **argv) {

	// initialize variables for fibonacci numbers
	int a = 1, b = 2, temp;

	// loop while the first fibonacci number is less than four million
	int total = 0;
	while (a < 4e6) {

		// add it to the running total if divisible by two
		if (!(a%2)) total += a;

		// update the fibonacci number values
		temp = a + b;
		a = b; b = temp;

	}

	// output the answer
	printf("the answer is %d.\n", total);

}
